syntax = "proto3";

package mainpb;

option go_package = "/proto/gen;genpb";

service Calculator {
    rpc GenerateFibonacci (FibonacciRequest) returns (stream FibonacciResponse); // Server Side Stream
    rpc SendNumbers (stream NumberRequest) returns (NumberResponse);             // Client Side Stream
    rpc Chat (stream ChatMessage) returns (stream ChatMessage);                  // Bi-Directional Stream
}

message ChatMessage {
    string Message = 1;
}

message NumberRequest {
    int32 Number = 1;
}

message NumberResponse {
    int32 Sum = 1;
}

message FibonacciRequest {
    int32 N = 1;
}

message FibonacciResponse {
    int32 Number = 1;
}